pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                withMaven(traceability: true) {
                    bat encoding: 'Cp866', script: 'mvn -f Lesson17/pom.xml clean test'
                }
            }
            post {
                always {
                    allure includeProperties: false, jdk: '', results: [[path: 'Lesson17/target/allure-results']]
                }
            }
        }
    }
}